
#Bit detection
[BitDetection]
	#If ShouldYellAt32BitUsers is set to true, this is the message that will be displayed to the user.
	Message = "go download 64 bit java silly!"
	#Set to true to make itlt yell at people attempting to use 32x java for the modpack.
	ShouldYellAt32BitUsers = true

#Management of a dedicated server
[Server]
	#The name of the dedicated server to add.
	ServerName = "Server"
	#The ip of the dedicated server to add.
	ServerIP = "54.39.39.199:25565"
	#Set to true to have a dedicated server added to the server list ingame. The server will not overwrite others servers.
	AddDedicatedServer = true

#Display
[Display]
	#Set to true to attempt to use the icon assigned to the modpack by the technic launcher. 
	#This will take priority over loadCustomIcon
	useTechnicIcon = true
	#Change this value to change the name of the MineCraft window
	windowDisplayTitle = "Elkium"
	#Set to true to attempt to get the display name of the pack of the info json file \nThis will take priority over windowDisplayTitle
	useTechnicDisplayName = false
	#Set to true to load a custom icon from config\itlt\icon.png
	loadCustomIcon = true

