
#General settings for the mod.
[general]
	#Should the names of mods be added to the pool of splashes?
	includeModNames = false
	#Should vanilla splash texts still be in the splash pool?
	includeVanillaSplashes = false
	#A list of additional splash texts that can be displayed.
	customSplashes = ["Elkium 0.5.1", "Fuck bisecthosting", "Cuong kills cows", "Ferda"]

