
#General settings for the mod.
[general]
	#Should the names of mods be added to the pool of splashes?
	includeModNames = false
	#Should vanilla splash texts still be in the splash pool?
	includeVanillaSplashes = false
	#A list of additional splash texts that can be displayed.
	customSplashes = ["Elkium 0.5.1", "Fuck bisecthosting", "Cuong kills cows", "Ferda", "This is a somewhat long splash, It's here to tell you that its long and it wants to slide in your dms. So you gonna let it or nah? Dudes LONG."]

